name: Cross-Platform CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-build:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { cpp_comp: "g++", c_comp: "gcc" }
          - { cpp_comp: "clang++", c_comp: "clang" }

    steps:
      - uses: actions/checkout@v4

      - name: Create metadata files
        run: |
          echo "Quadratic equation solver" > DESCRIPTION
          echo "MIT License" > LICENSE.txt
          echo "# Solver Application" > README.md

      - name: Install dependencies
        run: sudo apt-get install -y rpm

      - name: Configure CMake
        run: cmake -B _build -DCMAKE_CXX_COMPILER=${{matrix.config.cpp_comp}} -DCMAKE_C_COMPILER=${{matrix.config.c_comp}} -DCPACK_PACKAGE_ICON=""

      - name: Build project
        run: cmake --build _build --parallel

      - name: Run tests
        run: |
          echo "1 -5 6" | _build/solver_application/solver_app
          _build/hello_world_application/hello_world

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-${{matrix.config.c_comp}}
          path: _build/
          retention-days: 1

  windows-build:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create metadata files
        run: |
          echo "Quadratic equation solver" > DESCRIPTION
          echo "MIT License" > LICENSE.txt
          echo "# Solver Application" > README.md

      - name: Configure CMake
        run: cmake -B _build -DCPACK_PACKAGE_ICON=""

      - name: Build project (Release)
        run: cmake --build _build --config Release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: _build/
          retention-days: 1

  macos-build:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create metadata files
        run: |
          echo "Quadratic equation solver" > DESCRIPTION
          echo "MIT License" > LICENSE.txt
          echo "# Solver Application" > README.md

      - name: Configure CMake
        run: cmake -B _build -DCPACK_PACKAGE_ICON=""

      - name: Build project
        run: cmake --build _build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: _build/
          retention-days: 1

  create-packages:
    name: Create Packages
    needs: [linux-build, windows-build, macos-build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        shell: bash
        run: |
          version=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get install -y rpm libarchive-tools

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: _build

      - name: Generate packages
        shell: bash
        run: |
          cd _build
          mkdir -p artifacts
          
          cpack --config CPackSourceConfig.cmake -G "TGZ;ZIP"
          cpack -G "DEB"
          cpack -G "RPM"
          
          mv *.tar.gz artifacts/
          mv *.zip artifacts/
          mv *.deb artifacts/
          mv *.rpm artifacts/

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: release-packages
          path: _build/artifacts/
          retention-days: 1

  create-release:
    name: Create Release
    needs: create-packages
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: release-packages
          path: release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Solver v${{ env.VERSION }}"
          body: |
            ## Solver Application v${{ env.VERSION }}

            ### Packages included:
            - Linux: DEB, RPM, TGZ, ZIP
            - Windows: ZIP
            - macOS: TGZ
          files: |
            release-files/*
          draft: false
          prerelease: false
