name: Linux CI Pipeline

on: [push, pull_request]

jobs:
  linux-build:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { cpp_comp: "g++", c_comp: "gcc" }
          - { cpp_comp: "clang++", c_comp: "clang" }

    steps:
      - uses: actions/checkout@v4

      - name: Create required CPack files
        run: |
          echo "Simple project description" > DESCRIPTION
          echo "MIT License" > LICENSE.txt
          echo "# Project README" > README.md

      - name: Configure CMake
        run: cmake -H. -B_build -DCMAKE_CXX_COMPILER=${{matrix.config.cpp_comp}} -DCMAKE_C_COMPILER=${{matrix.config.c_comp}}

      - name: Build project
        run: cmake --build _build

      - name: Test executables
        run: |
          echo "1 -5 6" | _build/solver_application/solver_app
          _build/hello_world_application/hello_world

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-${{matrix.config.c_comp}}
          path: _build/
          retention-days: 1
